allow-uncaught: false
async-only: false
bail: false
check-leaks: false
color: true
delay: false
diff: true
exit: false

growl: false
inline-diffs: false
# needs to be used with grep or fgrep
# invert: false
jobs: 1
package: './package.json'
reporter: 'spec'
retries: 1
spec:
  - 'test/**/*.spec.ts' # the positional arguments!
timeout: '6000' # same as "timeout: '2s'"
# timeout: false # same as "timeout: 0"
trace-warnings: true # node flags ok
ui: 'bdd'
v8-stack-trace-limit: 100 # V8 flags are prepended with "v8-"
watch: false
watch-files:
  - 'test/**/*.ts'